import type { Metadata } from 'next';
import ThemeProvider from '@/services/ThemeProvider';
import { Poppins } from 'next/font/google';
import Header from './components/Header';
import './globals.css';

const poppins = Poppins({ weight: ['500', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang='en'>
   <body className={poppins.className}>
    <ThemeProvider attribute='data-mode' defaultTheme='light' enableSystem>
     <Header />
     {children}
    </ThemeProvider>
   </body>
  </html>
 );
}
